<?php

namespace AppBundle\Repository;

/**
 * PasswordResetTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordResetTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
