<?php

namespace AppBundle\Repository;

/**
 * UnavailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnavailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
