services:
#    dup_user.example:
#        class: Dup\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#
#    dup_baab.baab_cms.admin.user:
#        class: Dup\UserBundle\Admin\UserAdmin
#        arguments:
#            - ''
#            - Dup\UserBundle\Entity\User
#            - 'SonataAdminBundle:CRUD'
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: 'Basic CMS', label: Utilisateurs }
#        calls:
#            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    fos_user.doctrine_registry:
        alias: doctrine

    dup_user.keep_online:
        class: Dup\UserBundle\Service\KeepOnline
        arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']
        tags :
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    dup_user.role_manager:
        class: Dup\UserBundle\Service\RoleManager
        tags:
            - { name: doctrine.orm.entity_listener }

    dup_user.param_setter_listener:
        class: Dup\UserBundle\Service\UserParamSetterListener
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: doctrine.orm.entity_listener, lazy : true }
