app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

admin:
    resource: '@AppBundle/Controller/AdminController.php'
    type: annotation
    prefix: '/dashboard'

dup_user:
    resource: "@DupUserBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
